name: Build C code
on: [push, pull_request]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install GCC and Make
      run: sudo apt-get install build-essential

    - name: Compile emusetun.c
      run: make

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install GCC and Make
      run: |
        choco install mingw
        choco install make

    - name: Compile emusetun.c
      run: mingw32-make

  - name: 'Tar files'
    run: tar -cvf Emulator-Setup-1958.tar ../../../Emulator-Setup-1958

  - name: 'Upload Artifact'
    uses: actions/upload-artifact@v2
    with:
      name: Emulator-Setup-1958
      path: Emulator-Setup-1958.tar