name: Build and publish

on:
    push:
        tags:
            - "*"

jobs:
    build:
        name: Build for ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                      artifact_name: setun1958emu
                    - os: windows-latest
                      artifact_name: setun1958emu.exe

        steps:
            - uses: actions/checkout@v1.86

            - run: mkdir dist

            - name: Build for Linux
              if: matrix.os == 'ubuntu-latest'
              run: gcc emusetun.c -o setun1958emu

            - name: Build for Windows
              if: matrix.os == 'windows-latest'
              run: gcc emusetun.c -o setun1958emu.exe

            - name: Upload binaries to release
              uses: svenstaro/upload-release-action@v1.86
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: dist/${{ matrix.artifact_name }}
                  asset_name: ${{ matrix.asset_name }}
                  tag: ${{ github.ref }}
