name: Build, Zip and Upload C Program

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          sudo apt-get update && sudo apt-get install -y build-essential zip
        elif [ "${{ matrix.os }}" == "windows-latest" ]; then
          choco install -y mingw zip
        fi

    - name: Build emusetun
      run: make

    - name: Zip Emulator-Setun-1958
      run: zip -r Emulator-Setun-1958.zip setun1958emu