name: Build and Deploy C code
on: [push, pull_request]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install GCC and Make
      run: sudo apt-get install build-essential

    - name: Compile emusetun.c
      run: make

    - name: Archive main executable
      uses: montudor/action-zip@v0.2.0
      with:
        args: zip setun1958emu.zip setun1958emu

    - name: Upload main executable
      uses: actions/upload-artifact@v2
      with:
        name: setun1958emu
        path: setun1958emu.zip

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install GCC and Make
      run: |
        choco install mingw
        choco install make

    - name: Compile emusetun.c
      run: mingw32-make

    - name: Archive main executable
      uses: montudor/action-zip@v0.2.0
      with:
        args: zip setun1958emu.zip setun1958emu.exe

    - name: Upload main executable
      uses: actions/upload-artifact@v2
      with:
        name: setun1958emu
        path: setun1958emu.zip

  deploy:
    needs: [build-ubuntu, build-windows]
    runs-on: ubuntu-latest

    steps:
    - name: Download main executable
      uses: actions/download-artifact@v2
      with:
        name: setun1958emu

    - name: Install SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Deploy main executable
      run: scp setun1958emu.zip ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:${{ secrets.SERVER_PATH }}
